// <auto-generated />
using System;
using Data.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(RelationalDbContext))]
    partial class RelationalDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BusinessEntities.Order", b =>
                {
                    b.Property<Guid>("Identifier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("Customer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Identifier");

                    b.ToTable("Order");

                    b.HasData(
                        new
                        {
                            Identifier = new Guid("78121743-27ac-4f16-bb75-9a388f79255f"),
                            Customer = "Neville",
                            ProductId = new Guid("5ed5521b-c789-4c69-9aa5-c60cb478ab0a")
                        },
                        new
                        {
                            Identifier = new Guid("ea54efcb-dea9-4ace-8975-3d2680ced971"),
                            Customer = "Neville",
                            ProductId = new Guid("6d7e650e-c8e2-452a-a98c-f57b5e480db6")
                        });
                });

            modelBuilder.Entity("BusinessEntities.Product", b =>
                {
                    b.Property<Guid>("Identifier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("OrderIdentifier")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Identifier");

                    b.HasIndex("OrderIdentifier");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            Identifier = new Guid("5ed5521b-c789-4c69-9aa5-c60cb478ab0a"),
                            Description = "Industrial Robotic Arm",
                            Name = "Fanuc i90"
                        },
                        new
                        {
                            Identifier = new Guid("6d7e650e-c8e2-452a-a98c-f57b5e480db6"),
                            Description = "Industrial Robotic Arm",
                            Name = "Fanuc i30"
                        });
                });

            modelBuilder.Entity("BusinessEntities.Product", b =>
                {
                    b.HasOne("BusinessEntities.Order", null)
                        .WithMany("Products")
                        .HasForeignKey("OrderIdentifier");
                });

            modelBuilder.Entity("BusinessEntities.Order", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
